FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:0.2.5

RUN apt-get update && \
    apt-get install -y libglib2.0-dev:arm64 libgstreamer1.0-dev:arm64 \
    libgstreamer-plugins-base1.0-dev:arm64 libpcre3-dev:arm64 \
    zlib1g-dev:arm64 && \
    rm -rf /var/lib/apt/lists/*
