[package]
name = "stream-test-only"
version = "0.1.0"
edition = "2021"

[dependencies]
gstreamer = "0.25"
gstreamer-video = "0.25"
gstreamer-rtp = "0.25"
gstreamer-app = "0.25"
gstreamer-audio = "0.25"
anyhow = "1"
thiserror = "2"
tracing = "0.1"
tokio = { version = "1", features = ["sync"] }
